In [1]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [2]:
import numpy as np

In [4]:
arr = np.array(my_list)

In [5]:
arr

array([1, 2, 3])

In [7]:
my_mat = [[1,2,3],[5,6,7],[8,9,6]]
np.array(my_mat)

array([[1, 2, 3],
       [5, 6, 7],
       [8, 9, 6]])

In [9]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [11]:
np.zeros(3)

array([0., 0., 0.])

In [13]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [26]:
np.linspace(0,5,5)

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [31]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [38]:
np.random.rand()

0.5665809996456705

In [39]:
np.random.rand(5)


array([0.8064249 , 0.32773639, 0.60676713, 0.97676536, 0.29440988])

In [42]:
np.random.rand(3,3)

array([[0.85031139, 0.43421731, 0.16385248],
       [0.08513846, 0.43760852, 0.13418026],
       [0.38790223, 0.5938359 , 0.82945417]])

In [46]:
np.random.randn(2)

array([-0.66594712,  0.63583299])

In [51]:
np.random.randint(1,100)

75

In [52]:
np.random.randint(1,100,10)


array([36, 25, 66, 93, 39, 53, 35, 45, 23, 86])

In [59]:
arr = np.arange(25)
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [58]:
ranarr = np.random.randint(0,50,10)
ranarr

array([26, 11, 34,  8, 37,  3,  2, 22,  0,  2])

In [60]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [61]:
ranarr

array([26, 11, 34,  8, 37,  3,  2, 22,  0,  2])

In [62]:
ranarr.max()

37

In [63]:
ranarr.min()

0

In [64]:
ranarr.argmax()

4

In [65]:
ranarr.argmin()

8

In [68]:
arr = arr.reshape(5,5)

In [69]:
arr.shape

(5, 5)

In [70]:
arr.dtype

dtype('int32')

In [71]:
from numpy.random import randint

In [2]:
randint(2,10)

NameError: name 'randint' is not defined

In [3]:
import numpy as np

In [5]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
arr[0]

0

In [9]:
arr[1:5]

array([1, 2, 3, 4])

In [10]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [11]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [12]:
arr[0:5] = 100

In [13]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [14]:
arr = np.arange(0,11)

In [15]:
slice_of_arr = arr[0:6]

In [16]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [17]:
slice_of_arr[:] = 99

In [18]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [19]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [20]:
arr_copy = arr.copy()

In [21]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [22]:
arr_copy[:] = 100

In [23]:
arr_2d = np.array([[5,10,15,],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [24]:
arr_2d[0][0]

5

In [25]:
arr_2d[1][1]

25

In [26]:
arr_2d[2][0]

35

In [27]:
arr_2d[2,0]

35

In [28]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [29]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [30]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [32]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [38]:
bool_arr = arr > 50

In [39]:
bool_arr

array([ True,  True,  True,  True,  True,  True, False, False, False,
       False, False])

In [40]:
arr[bool_arr]

array([99, 99, 99, 99, 99, 99])

In [42]:
arr[arr > 50]

array([99, 99, 99, 99, 99, 99])

In [45]:
arr_2d = np.arange(50).reshape(5,10)
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [48]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])